### ISSUE TITLE
Unclear 'colors' API parameter for "Palette" animation type

### ISSUE THREAD

**Issue by AlejandorLazaro** [Luca3317/TMPEffects-Pages#2]
## Summary

In the [TMPAnimator "Built-in animations"](https://tmpeffects.luca3317.dev/docs/tmpanimator_builtinbasicanimations.html) page, the "Palette" animation help notes that it accepts Colors as a parameter, but—as far as I've seen—doesn't detail how to provide *multiple* colors to cycle through for that animation style.

Unity's official docs also only show a single color supported for rich text tags, so added detail here would be useful.

E.g.: The following code would have a wavy "human" text in blue, but how would a user make it cycle between red, white, and blue?
```
<palette clrs=blue><wave late>USA</wave></palette>
```
![USA](https://github.com/user-attachments/assets/92c0e47c-bfdb-4e75-b7e6-602c1c889c9a)

https://docs.unity3d.com/2018.3/Documentation/Manual/StyledText.html

**If** only one color is supported, updating the documentation to reflect that (and that the default behavior without a color set is to cycle through the rainbow) would be great.

**Comment by Luca3317** [comment]
The colors parameter on \<palette> is a color array; see the [parameter types docs](https://tmpeffects.luca3317.dev/docs/parametertypes.html) for how to apply that (in your case it'd be \<palette clrs=red;white;blue>)

Im gonna go ahead and add the type to each parameter in the docs

**Comment by AlejandorLazaro** [comment]
Awesome! Somehow I had *completely* missed that Parameters page, but that’ll help clear things up immensely.

Appreciate your quick feedback and turnaround time for these changes! 😊
